version: "3.3"
services:
  app-love:
    container_name: app-love
    image: openjdk:8
    restart: always
    ports:
      - 9121:9121
    volumes:
      - ./app/app-love.jar:/app-love.jar
      - ./app/logs:/logs/
      # 指定容器时间为宿主机时间
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
    entrypoint: java -server -Xms512m -Xmx512m -Xmn200m -Xss256k -jar -Dserver.port=9121 -Dspring.profiles.active=dev /app-love.jar
  ali-nginx:
    container_name: ali-nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/html/dist:/usr/share/nginx/html
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
    environment:
      - TZ=Asia/Shanghai
