version: "3.3"
services:
  app-admin:
    container_name: app-admin
    image: openjdk:8
    restart: always
    ports:
      - 9000:8080
    volumes:
      - /var/local/workspace/java/app-admin/app.jar:/app.jar
      - /var/local/workspace/java/app-admin/attachment:/var/attachment
      - /var/local/workspace/java/app-admin/logs:/logs/
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
    entrypoint: java -server -Xms50m -Xmx245m -Xmn200m -Xss256k -jar -Dserver.port=8080 -Dspring.profiles.active=dev /app.jar
    networks:
      extnetwork:
  momo-stock-index:
    container_name: momo-stock-index
    image: openjdk:8
    restart: always
    ports:
      - 8001:8080
    volumes:
      - /var/local/workspace/java/momo-stock-index/app.jar:/app.jar
      - /var/local/workspace/java/momo-stock-index/logs:/logs/
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
    entrypoint: java -server -Xms50m -Xmx256m -Xmn200m -Xss256k -jar -Dserver.port=8080 -Dspring.profiles.active=prod /app.jar
    networks:
      extnetwork:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/html/dist:/usr/share/nginx/html
      - ./nginx/xiaokai:/usr/share/nginx/xiaokai
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
      - /root/w/cert/fund.lyloou.com:/cert
      - /root/w/python/data:/fund
      #- /root/w/fund/data:/fund2
      - /root/w/momo-all/momo-python/fund/data:/fund2
    environment:
      - TZ=Asia/Shanghai
    networks:
      extnetwork:
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    environment:
      - TZ=Asia/Shanghai
    entrypoint: redis-server /usr/local/etc/redis/redis.conf
    networks:
      extnetwork:
  mysql57:
    container_name: mysql57
    image: mysql:5.7.31
    restart: always
    ports:
      - 3306:3306
    privileged: true
    volumes:
      - ./mysql57/log:/var/log/mysql 
      - ./mysql57/conf/my.cnf:/etc/mysql/my.cnf
      - ./mysql57/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "lyloou@06"
      MYSQL_USER: 'lyloou'
      MYSQL_PASS: 'lyloou@06'
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_general_ci',
        '--max_connections=3000'
    ]
    networks:
      extnetwork:
  memos:
    container_name: memos
    image: ghcr.io/usememos/memos:latest
    restart: always
    ports:
      - 5230:5230
    volumes:
      - /root/w/memos/data:/var/opt/memos
    environment:
      - TZ=Asia/Shanghai
    networks:
      extnetwork:
networks:
  extnetwork:
    ipam:
      config:
        - subnet: 172.18.0.1/16
