version: "3.3"
services:
  app-admin:
    container_name: app-admin
    image: openjdk:8
    restart: always
    ports:
      - 9000:8080
    volumes:
      - /var/local/workspace/java/app-admin/app.jar:/app.jar
      - /var/local/workspace/java/app-admin/attachment:/var/attachment
      - /var/local/workspace/java/app-admin/logs:/logs/
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
    entrypoint: java -server -Xms50m -Xmx245m -Xmn200m -Xss256k -jar -Dserver.port=8080 -Dspring.profiles.active=dev /app.jar
    networks:
      extnetwork:
  momo-stock-index:
    container_name: momo-stock-index
    image: openjdk:8
    restart: always
    ports:
      - 8001:8080
    volumes:
      - /var/local/workspace/java/momo-stock-index/app.jar:/app.jar
      - /var/local/workspace/java/momo-stock-index/logs:/logs/
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
    entrypoint: java -server -Xms50m -Xmx256m -Xmn200m -Xss256k -jar -Dserver.port=8080 -Dspring.profiles.active=prod /app.jar
    networks:
      extnetwork:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/html/dist:/usr/share/nginx/html
      - ./nginx/xiaokai:/usr/share/nginx/xiaokai
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
      - /root/w/cert/fund.lyloou.com:/cert
      - /root/w/python/data:/fund
      #- /root/w/fund/data:/fund2
      - /root/w/momo-all/momo-python/fund/data:/fund2
      - ./certbot/www:/usr/share/certbot/www:ro
      - ./certbot/ssl:/usr/share/certbot/ssl:ro
    command:  nginx -g 'daemon off;'
    environment:
      - TZ=Asia/Shanghai
    networks:
      extnetwork:
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www:/usr/share/certbot/www:rw
      - ./certbot/ssl:/etc/letsencrypt:rw
    networks:
      extnetwork:
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    environment:
      - TZ=Asia/Shanghai
    entrypoint: redis-server /usr/local/etc/redis/redis.conf
    networks:
      extnetwork:
  mysql57:
    container_name: mysql57
    image: mysql:5.7.31
    restart: always
    ports:
      - 3306:3306
    privileged: true
    volumes:
      - ./mysql57/log:/var/log/mysql 
      - ./mysql57/conf/my.cnf:/etc/mysql/my.cnf
      - ./mysql57/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "lyloou@06"
      MYSQL_USER: 'lyloou'
      MYSQL_PASS: 'lyloou@06'
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_general_ci',
        '--max_connections=3000'
    ]
    networks:
      extnetwork:
  memos:
    container_name: memos
    image: ghcr.io/usememos/memos:latest
    restart: always
    ports:
      - 5230:5230
    volumes:
      - /root/w/memos/data:/var/opt/memos
    environment:
      - TZ=Asia/Shanghai
    networks:
      extnetwork:
  minio:
    image: minio/minio:latest 
    container_name: minio 
    restart: unless-stopped
    volumes: 
      - "./minio/data:/data"
      - "./minio/minio:/minio"
      - "./minio/config:/root/.minio"
    environment: 
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
      MINIO_ACCESS_KEY: "root" 
      MINIO_SECRET_KEY: "lyloou06" 
      MINIO_SERVER_URL: "http://box-api.lyloou.com"
    command: server /data  --console-address ":9010" --address ":9009"
    ports: 
      - "9010:9010"
      - "9009:9009"
    networks:
      extnetwork:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./mongo/database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: lyloou06
    networks:
      extnetwork:
#  mongo-express:
#    image: mongo-express
#    container_name: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
#      ME_CONFIG_MONGODB_ADMINPASSWORD: lyloou06
#      ME_CONFIG_MONGODB_SERVER: mongodb
#    networks:
#      extnetwork:
networks:
  extnetwork:
    ipam:
      config:
        - subnet: 172.18.0.1/16
